# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 19:16
from __future__ import unicode_literals

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_update_complain_states'),
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.AlterField(
            model_name='complaint',
            name='current_state',
            field=models.IntegerField(choices=[(1, 'Dirty'), (2, 'Clean')], default=1),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='picture',
            field=models.URLField(),
        ),
    ]
