# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 19:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_replacing_picture_and_states_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='tweet_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
