# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 17:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_allow_empty_values_tweet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='tweet_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
